### ISSUE TITLE
Distillation recipes show incorrect fluid amounts

### ISSUE THREAD

**Issue by Xfel** [mnorfolk03/StarEI#1]
The rei recipes in the distillation tab always show the fluid amounts as 1 Bucket, no matter what the actual amount is.

**Comment by mnorfolk03** [comment]
> The rei recipes in the distillation tab always show the fluid amounts as 1 Bucket, no matter what the actual amount is.

Next update I will try to fix this -- good find

**Comment by mnorfolk03** [comment]
Fixed in 1.0.1
